on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Get previous tag'
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@master
      - name: 'Semantic version check'
        run: ./sript/check-semver ${{ steps.previous_tag.outputs.tag }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
